'use strict';
(()=>{
 const api='https://synbot-whatsapp-2.onrender.com/nexora/admin';
 const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(n/100),date=n=>new Date(n*1000).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});
 let token='',snapshot=null,view='overview',selected=null,finish=null,expiryTimer,stockAction=null,shipmentAction=null;
 const names={unfulfilled:'Unfulfilled',packed:'Packed',shipped:'Shipped',delivered:'Delivered',on_hold:'On hold',review:'Payment review'};
 function logout(message=''){token='';snapshot=null;selected=null;clearTimeout(expiryTimer);$('workspace').hidden=true;$('login-view').hidden=false;$('password').value='';$('login-message').textContent=message;for(const id of ['order-table','recent-orders','order-detail','stock-history','stock-summary','inventory-cards'])$(id).replaceChildren();document.querySelectorAll('dialog[open]').forEach(x=>x.close())}
 async function request(path,options={}){const r=await fetch(api+path,{...options,cache:'no-store',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{}),...options.headers}});let d;try{d=await r.json()}catch{throw Error('The service is temporarily unavailable. Please retry.')}if(r.status===401&&token){logout('Your session expired. Please sign in again.');throw Error('Please sign in again.')}if(!r.ok)throw Error(d.error||'Could not complete this request.');return d}
 const badge=o=>{const s=o.refunded||o.disputed?'review':o.fulfilment.status;return '<span class="badge '+esc(s)+'">'+esc(names[s]||s)+'</span>'};
 const empty=(title,copy)=>'<div class="empty"><span class="empty-icon">◈</span><strong>'+esc(title)+'</strong><p>'+esc(copy)+'</p></div>';
 function render(){
  const {summary:s,orders,complete}=snapshot;
  $('stat-orders').textContent=s.orders;$('stat-revenue').textContent=money(s.net);$('stat-units').textContent=s.units;$('stat-ship').textContent=s.toShip;$('order-count').textContent=s.orders;
  $('sync-status').textContent='Updated '+new Date(snapshot.updated).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})+' · Stripe-confirmed payments';$('incomplete-warning').hidden=complete;
  $('recent-orders').innerHTML=orders.length?orders.slice(0,5).map(o=>'<div class="recent-row"><button data-order="'+esc(o.id)+'">'+esc(o.customer.name||'Customer')+'<small>#'+esc(o.reference)+' · '+date(o.created)+'</small></button>'+badge(o)+'<span>'+money(o.amount)+'</span></div>').join(''):empty('Your first order starts here.','Confirmed MI-1 payments will appear automatically. Refresh to check for new orders.');
  $('stock-summary').innerHTML=s.stock.map(x=>'<div class="stock-row"><span class="swatch '+x.finish+'"></span><span>MI-1 · '+(x.finish==='black'?'Black':'White')+'</span><strong>'+esc(x.available===null?'Not set':x.available)+'</strong></div>').join('');
  $('inventory-cards').innerHTML=s.stock.map(x=>'<article class="inventory-card"><h3><span class="swatch '+x.finish+'"></span>MI-1 · '+(x.finish==='black'?'Black':'White')+'</h3><span class="available">'+esc(x.available===null?'Not set':x.available)+'</span><span class="muted small">'+(x.available===null?'Enter your stock to begin':x.available<0?'Stock shortfall — review before taking more orders':'Available after paid orders')+'</span><div class="breakdown"><span>Received / adjusted<b>'+x.received+'</b></span><span>Units sold<b>'+x.sold+'</b></span></div><button class="secondary" data-stock="'+x.finish+'">'+(x.configured?'Adjust stock':'Set opening stock')+' ↗</button></article>').join('');
  $('stock-history').innerHTML=snapshot.stockHistory.length?'<table><thead><tr><th>Date</th><th>Finish</th><th>Change</th><th>Reason</th></tr></thead><tbody>'+snapshot.stockHistory.map(r=>'<tr><td>'+esc(new Date(r.at).toLocaleString())+'</td><td>'+esc(r.change.finish)+'</td><td>'+(r.change.delta>0?'+':'')+r.change.delta+'</td><td>'+esc(r.change.reason)+'</td></tr>').join('')+'</tbody></table>':empty('No stock recorded yet.','Enter the actual units received. We never assume supplier stock.');
  renderOrders();
 }
 function filtered(){const q=$('search').value.trim().toLowerCase(),s=$('status-filter').value;return snapshot.orders.filter(o=>(!q||[o.customer.name,o.customer.email,o.reference].join(' ').toLowerCase().includes(q))&&(s==='all'||(s==='review'?(o.refunded||o.disputed):o.fulfilment.status===s))&&(view!=='fulfilment'||!['delivered'].includes(o.fulfilment.status)))}
 function renderOrders(){if(!snapshot)return;const rows=filtered();$('order-table').innerHTML=rows.length?'<table><thead><tr><th>Order</th><th>Customer</th><th>Items</th><th>Paid</th><th>Status</th><th></th></tr></thead><tbody>'+rows.map(o=>'<tr><td>#'+esc(o.reference)+'<small>'+date(o.created)+'</small></td><td>'+esc(o.customer.name||'Customer')+'<small>'+esc(o.customer.email)+'</small></td><td>'+o.items.map(i=>esc(i.qty+' × '+i.finish)).join('<br>')+'</td><td>'+money(o.amount)+(o.refunded?'<small>'+money(o.refunded)+' refunded</small>':'')+'</td><td>'+badge(o)+'</td><td><button data-order="'+esc(o.id)+'">View ↗</button></td></tr>').join('')+'</tbody></table>':empty('Nothing here just yet.','No orders match this view. Try another filter or refresh for new payments.')}
 function showView(next){view=next;for(const n of ['overview','orders','inventory'])$(n+'-view').hidden=n!==(view==='fulfilment'?'orders':view);document.querySelectorAll('.sidebar [data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===next));$('breadcrumb').textContent=next.toUpperCase();$('page-title').textContent={overview:'Your store, at a glance.',orders:'Every order. One place.',inventory:'Know what’s ready.',fulfilment:'From your shelf to their home.'}[next];$('orders-heading').textContent=next==='fulfilment'?'Fulfilment queue':'Orders';$('search').value='';$('status-filter').value='all';renderOrders()}
 async function refresh(force=true){$('refresh').disabled=true;$('app-message').hidden=true;try{snapshot=await request('/snapshot'+(force?'?refresh=1':''));render()}catch(e){$('app-message').textContent=e.message;$('app-message').hidden=false;$('sync-status').textContent='Could not update · Existing information may be out of date'}finally{$('refresh').disabled=false}}
 function openOrder(id){selected=snapshot.orders.find(o=>o.id===id);if(!selected)return;shipmentAction=null;const o=selected,a=o.customer.address;const address=a?[a.line1,a.line2,[a.city,a.state,a.postal_code].filter(Boolean).join(', '),a.country].filter(Boolean).join('\n'):'No shipping address recorded. Review in Stripe.';$('detail-title').textContent='#'+o.reference;$('order-detail').innerHTML=badge(o)+'<div class="detail-grid"><div><strong>Customer</strong><p>'+esc(o.customer.name)+'\n'+esc(o.customer.email)+'</p></div><div><strong>Ship to</strong><p>'+esc(address)+'</p></div></div><div class="detail-items">'+o.items.map(i=>'<div><span>'+esc(i.qty+' × '+i.name)+'</span><span>'+money(i.amount)+'</span></div>').join('')+'<div><b>Total paid</b><b>'+money(o.amount)+'</b></div></div><a class="text-button" target="_blank" rel="noopener noreferrer" href="https://dashboard.stripe.com/payments/'+encodeURIComponent(o.paymentId)+'">Review payment in Stripe ↗</a>'+((o.refunded||o.disputed)?'<p class="notice">Refund or dispute detected. Keep this order on hold until reviewed. Refunds do not automatically return stock.</p>':'');$('fulfilment-status').value=o.fulfilment.status;$('carrier').value=o.fulfilment.carrier||'';$('tracking').value=o.fulfilment.tracking||'';$('shipment-note').value=o.fulfilment.note||'';$('shipment-message').textContent='';$('order-dialog').showModal()}
 document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view)showView(b.dataset.view);if(b.dataset.order)openOrder(b.dataset.order);if(b.dataset.close)$(b.dataset.close).close();if(b.dataset.stock){finish=b.dataset.stock;stockAction=null;$('stock-title').textContent='MI-1 · '+(finish==='black'?'Black':'White');$('stock-form').reset();$('stock-message').textContent='';$('stock-dialog').showModal()}});
 $('login-form').addEventListener('submit',async e=>{e.preventDefault();$('sign-in').disabled=true;$('login-message').textContent='Signing in securely…';try{const data=await request('/login',{method:'POST',body:JSON.stringify({email:$('email').value,password:$('password').value})});token=data.accessToken;$('password').value='';$('owner-email').textContent=data.email;$('login-view').hidden=true;$('workspace').hidden=false;expiryTimer=setTimeout(()=>logout('Your secure session expired. Sign in again.'),Math.max(1,data.expiresIn-20)*1000);await refresh()}catch(e){$('login-message').textContent=e.message}finally{$('sign-in').disabled=false}});
 $('shipment-form').addEventListener('submit',async e=>{e.preventDefault();if(!selected)return;$('save-shipment').disabled=true;const change={status:$('fulfilment-status').value,carrier:$('carrier').value,tracking:$('tracking').value,note:$('shipment-note').value};const payload=JSON.stringify(change);if(!shipmentAction||shipmentAction.payload!==payload)shipmentAction={id:crypto.randomUUID(),payload};try{await request('/orders/'+encodeURIComponent(selected.id)+'/fulfilment',{method:'POST',headers:{'Idempotency-Key':shipmentAction.id},body:payload});$('order-dialog').close();await refresh(false)}catch(e){$('shipment-message').textContent=e.message}finally{$('save-shipment').disabled=false}});
 $('stock-form').addEventListener('submit',async e=>{e.preventDefault();$('save-stock').disabled=true;const payload=JSON.stringify({finish,delta:Number($('stock-delta').value),reason:$('stock-reason').value});if(!stockAction||stockAction.payload!==payload)stockAction={id:crypto.randomUUID(),payload};try{await request('/stock',{method:'POST',headers:{'Idempotency-Key':stockAction.id},body:payload});$('stock-dialog').close();await refresh(false)}catch(e){$('stock-message').textContent=e.message}finally{$('save-stock').disabled=false}});
 $('search').addEventListener('input',renderOrders);$('status-filter').addEventListener('change',renderOrders);$('refresh').addEventListener('click',()=>refresh());$('logout').addEventListener('click',()=>logout());$('mobile-logout').addEventListener('click',()=>logout());
 $('export').addEventListener('click',()=>{const cell=v=>'"'+String(v??'').replace(/^[=+@\-\t\r]/,"'$&").replace(/"/g,'""')+'"';const rows=[['Order','Date','Customer','Email','Items','Paid USD','Refunded USD','Status','Carrier','Tracking'],...filtered().map(o=>[o.reference,new Date(o.created*1000).toISOString(),o.customer.name,o.customer.email,o.items.map(i=>i.qty+' x '+i.finish).join('; '),o.amount/100,o.refunded/100,o.fulfilment.status,o.fulfilment.carrier,o.fulfilment.tracking])];const url=URL.createObjectURL(new Blob(['\uFEFF'+rows.map(r=>r.map(cell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='nexora-orders-'+new Date().toISOString().slice(0,10)+'.csv';a.click();URL.revokeObjectURL(url)});
 request('/config').then(c=>{if(!c.ready)$('login-message').textContent='Your dashboard is being connected. Owner access must be configured before signing in.'}).catch(()=>{$('login-message').textContent='The store service is waking up. Please try signing in shortly.'});
})();
